version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: iN!nfxYNzwi-2dwY7ox3Vt7.J
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      # - wordpress:/var/www/html
      - ./www/:/var/www/html/

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: iN!nfxYNzwi-2dwY7ox3Vt7.J
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
