version: '3.1'

services:
  web:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpres_wp
    restart: always
    volumes:
      - wordpress:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: iN!nfxYNzwi-2dwY7ox3Vt7.J
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    ports:
      - 8585:80
    networks:
      - wp_network
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: iN!nfxYNzwi-2dwY7ox3Vt7.J
    networks:
      - wp_network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    ports:
      - 8686:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: iN!nfxYNzwi-2dwY7ox3Vt7.J
    networks:
      - wp_network
networks:
  wp_network:
volumes:
  wordpress:
  db_data:
